export type ProductionCatalogEntry = {
  id: number;
  name: string;
  origin_country: string;
  logo_path: null;
  note?: string;
};

export const PRODUCTION_CATALOG: readonly ProductionCatalogEntry[] = [
  { id: 2, name: "Walt Disney Pictures", origin_country: "US", logo_path: null, note: "Generations of spectacle, adventure, and family storytelling." },
  { id: 33, name: "Universal Pictures", origin_country: "US", logo_path: null, note: "A century-spanning home for monsters, blockbusters, and modern classics." },
  { id: 174, name: "Warner Bros. Pictures", origin_country: "US", logo_path: null, note: "Iconic characters and ambitious worlds from Hollywood’s golden age onward." },
  { id: 5, name: "Columbia Pictures", origin_country: "US", logo_path: null, note: "The torch-bearing studio behind comedy, drama, and global franchises." },
  { id: 4, name: "Paramount Pictures", origin_country: "US", logo_path: null, note: "Mountain-marked cinema, from enduring epics to crowd-pleasing franchises." },
  { id: 3, name: "Pixar", origin_country: "US", logo_path: null, note: "Emotionally precise animation where imagination and technology meet." },
  { id: 420, name: "Marvel Studios", origin_country: "US", logo_path: null, note: "A connected universe of heroes, legacies, and cinematic spectacle." },
  { id: 521, name: "DreamWorks Animation", origin_country: "US", logo_path: null, note: "Bold animated comedy, heart, and unconventional heroes." },
  { id: 41077, name: "A24", origin_country: "US", logo_path: null, note: "Singular filmmakers, daring perspectives, and contemporary cult favorites." },
  { id: 10342, name: "Studio Ghibli", origin_country: "JP", logo_path: null, note: "Hand-crafted wonder, ecological imagination, and deeply human journeys." },
  { id: 1, name: "Lucasfilm Ltd.", origin_country: "US", logo_path: null },
  { id: 7, name: "DreamWorks Pictures", origin_country: "US", logo_path: null },
  { id: 12, name: "New Line Cinema", origin_country: "US", logo_path: null },
  { id: 14, name: "Miramax", origin_country: "US", logo_path: null },
  { id: 21, name: "Metro-Goldwyn-Mayer", origin_country: "US", logo_path: null },
  { id: 56, name: "Amblin Entertainment", origin_country: "US", logo_path: null },
  { id: 79, name: "Village Roadshow Pictures", origin_country: "US", logo_path: null },
  { id: 81, name: "Plan B Entertainment", origin_country: "US", logo_path: null },
  { id: 508, name: "Regency Enterprises", origin_country: "US", logo_path: null },
  { id: 559, name: "TriStar Pictures", origin_country: "US", logo_path: null },
  { id: 923, name: "Legendary Pictures", origin_country: "US", logo_path: null },
  { id: 1632, name: "Lionsgate", origin_country: "US", logo_path: null },
  { id: 2251, name: "Sony Pictures Animation", origin_country: "US", logo_path: null },
  { id: 3172, name: "Blumhouse Productions", origin_country: "US", logo_path: null },
  { id: 6704, name: "Illumination", origin_country: "US", logo_path: null },
  { id: 7036, name: "CJ Entertainment", origin_country: "KR", logo_path: null },
  { id: 7493, name: "FilmNation Entertainment", origin_country: "US", logo_path: null },
  { id: 10146, name: "Focus Features", origin_country: "US", logo_path: null },
  { id: 10163, name: "Working Title Films", origin_country: "GB", logo_path: null },
  { id: 11461, name: "Bad Robot", origin_country: "US", logo_path: null },
  { id: 13184, name: "Annapurna Pictures", origin_country: "US", logo_path: null },
  { id: 82819, name: "Skydance Media", origin_country: "US", logo_path: null },
  { id: 127928, name: "20th Century Studios", origin_country: "US", logo_path: null },
  { id: 127929, name: "Searchlight Pictures", origin_country: "US", logo_path: null },
  { id: 184898, name: "DC Studios", origin_country: "US", logo_path: null },
  { id: 194232, name: "Apple Studios", origin_country: "US", logo_path: null },
  { id: 210099, name: "Amazon MGM Studios", origin_country: "US", logo_path: null },
  { id: 270158, name: "STX Entertainment", origin_country: "US", logo_path: null },
  { id: 9, name: "Gaumont", origin_country: "FR", logo_path: null },
  { id: 23, name: "Imagine Entertainment", origin_country: "US", logo_path: null },
  { id: 34, name: "Sony Pictures", origin_country: "US", logo_path: null },
  { id: 41, name: "Orion Pictures", origin_country: "US", logo_path: null },
  { id: 60, name: "United Artists", origin_country: "US", logo_path: null },
  { id: 97, name: "Castle Rock Entertainment", origin_country: "US", logo_path: null },
  { id: 104, name: "Canal+", origin_country: "FR", logo_path: null },
  { id: 288, name: "BBC Film", origin_country: "GB", logo_path: null },
  { id: 694, name: "StudioCanal", origin_country: "FR", logo_path: null },
  { id: 2785, name: "Warner Bros. Animation", origin_country: "US", logo_path: null },
  { id: 6125, name: "Walt Disney Animation Studios", origin_country: "US", logo_path: null },
  { id: 178464, name: "Netflix", origin_country: "US", logo_path: null },
];
